### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by vargalas** [begriffs/css-ratiocinator#58]
Just asking, because this looks really interesting.

**Comment by begriffs** [comment]
I haven't been actively developing it lately, but happy to accept pull requests and keep maintaining it.

(I think solving issue #29 would probably be the most significant improvement)

**Comment by begriffs** [comment]
Also let me know how it works for you. It should still function fine but I'm curious if it does what you hoped.

**Comment by gwern** [comment]
It might be a good idea to clarify this repo's status by formally archiving it. It has not had any commits in 9 years; and the biggest & most critical & hardest to fix dependency, [PhantomJS](https://github.com/ariya/phantomjs/issues/15344), has been archived for 6 years, so reviving css-ratiocinator is probably impossible at this point without a complete rewrite as a new project.

**Comment by begriffs** [comment]
> It might be a good idea to clarify this repo's status by formally
> archiving it.

While I don't plan to personally work on the project, I'm still willing
to review and accept pull requests.

> It has not had any commits in 9 years; and the biggest & most critical
> & hardest to fix dependency,
> [PhantomJS](https://github.com/ariya/phantomjs/issues/15344), has been
> archived for 6 years

Hm, how time flies. :) 

Is it possible to continue running ratiocinator using the final version
(v2.1.1) of PhantomJS? Although phantom may no longer be improving, I
don't use any of its advanced features. Any version should be OK.

Or is the issue that CSS is evolving and phantom doesn't recognize some
of the newer CSS constructs?
